### ISSUE TITLE
Can't login when password has spaces

### ISSUE THREAD

**Issue by adrpino** [agl/xmpp-client#100]
I cannot login in accounts that have spaces in the password. I have tried to enclose the password in quotes but it doesn't work. Should I type them with some special character?

**Comment by zeroshirts** [comment]
@adrpino curious, are you typing the password into xmpp-directly, or is it read from the json config file?

**Comment by adrpino** [comment]
@zeroshirts  I have the errors when inputting the password in the console and also when writing it in the configuration file, so I don't believe is an issue of the spaces themselves.

For testing purposes I have created a couple of accounts:
tests_agl_xmppclient@dukgo.com,  with password "test test"
tests_agl_xmppclient@jabber.otr.im,  with password also "test test"

I have checked a couple of times I can connect to both of them from Pidgin, but any can test it.

The weird thing is that from xmpp-client I manage to connect to the dukgo account, but not to the jabber.otr.im. If someone can connect to the second form xmpp-client, it will prove it's a problem on my computer.

Any Ideas?

**Comment by adrpino** [comment]
I have no idea about the fundamentals of how this program runs, and in principle I thought it was something about the password, but clearly it is not the case. The error I get is:

 Failed to connect via proxy: dial tcp 127.0.0.1:9050: getsockopt: connection refused.

**Comment by agl** [comment]
I can authenticate as tests_agl_xmppclient@dukgo.com with a space in the password without any issues, so I think that's working.

> Failed to connect via proxy: dial tcp 127.0.0.1:9050: getsockopt: connection refused.

That suggests that you enabled Tor, but don't have Tor running. (Or, at least, not on the default port.) If you don't want Tor enabled, you can edit your config file (`~/.xmpp-client` by default) and remove the "Proxies" section.

**Comment by adrpino** [comment]
Ok, now I got it, you said it. I haven't got Tor running. In my defense for such a blunder, I compiled xmpp-client a long ago and I didn't remember whether it included Tor in itself, I was confused with Ricochet.
