### ISSUE TITLE
Home / End keys don't do anything

### ISSUE THREAD

**Issue by aerth** [agl/xmpp-client#106]
are home and end keys expected to work?

**Comment by sycamoreone** [comment]
Yes. Search for `keyHome` and `keyEnd` in github.com/golang/crypto/blob/master/ssh/terminal/terminal.go for the implementation.

 The Home and End keys actually do work in an xterm window, but not in a gnome-terminal window (at least for me). ^A and ^E always seem to work though.

**Comment by aerth** [comment]
Thanks for the quick reply. I am using xfce4-terminal. ^A and ^E work thanks :+1:
