### ISSUE TITLE
license

### ISSUE THREAD

**Issue by aerth** [agl/xmpp-client#108]
I noticed the [LICENSE](https://github.com/agl/xmpp-client/blob/master/LICENSE) file says ``` Copyright (c) 2012 The Go Authors. All rights reserved. ```

I am not sure if this is entirely accurate. Thank you for a great piece of software!

I forked it but it was before I learned go

**Comment by mmcco** [comment]
If you're looking for a BSD-style license, the [ISC license](https://en.wikipedia.org/wiki/ISC_license) is probably the least likely to cause issues or have unintended implications.

To echo @aerth: thanks for your work!

**Comment by aerth** [comment]
What I really want is to know, "The Go Authors" is that who created xmpp-client?

**Comment by mmcco** [comment]
No. I assume that the author decided to use their license and forgot to change the Copyright holder.

**Comment by aerth** [comment]
Okay I am going to keep this open until LICENSE file changes!
