### ISSUE TITLE
custom root ca

### ISSUE THREAD

**Issue by deadElk** [agl/xmpp-client#111]
hi. 

how to provide custom root ca? 

thanx.

**Comment by agl** [comment]
The Go TLS library should pick up the root certificates from your OS. See, for example https://golang.org/src/crypto/x509/root_linux.go

**Comment by deadElk** [comment]
there is nothing of this on freebsd ... 
found this - https://golang.org/pkg/crypto/tls/ but i don't know what i need to do with this info ... 
please, help

**Comment by deadElk** [comment]
https://golang.org/src/crypto/x509/root_bsd.go 
doesn't help ... 

# xmpp-client 
 * (10:13AM) Making TCP connection to private.xmpp.server.:5222
 * (10:13AM) Starting TLS handshake
 * (10:13AM)   SSL/TLS version: TLS 1.2
 * (10:13AM)   Cipher suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
 * (10:13AM) Failed to connect to XMPP server: xmpp: failed to verify TLS certificate: x509: certificate signed by unknown authority

**Comment by deadElk** [comment]
https://golang.org/src/crypto/x509/root_bsd.go
helped 
thanx
