### ISSUE TITLE
Bug in setEqual function

### ISSUE THREAD

**Issue by zeroshirts** [agl/xmpp-client#76]
The [setEqual function](https://github.com/agl/xmpp-client/blob/8142601029916111c880f0c4b790d38959804170/ui.go#L1321-1337) in `ui.go` has a bug.  Basically, the labeled break should be a labeled continue.

Here's a test case that shows the breakage:
http://play.golang.org/p/3vqIJINTt_

**Comment by agl** [comment]
Thanks!
