### ISSUE TITLE
Client Connects To Incorrect .onion Address

### ISSUE THREAD

**Issue by praxis-journal** [agl/xmpp-client#79]
After selecting "Use Tor" in the initial configuration with a Riseup email address, xmpp-client tried to connect to: ztmc4p37hvues222.onion, which is no longer Riseup's hidden service xmpp gateway. It's now: 4cjw6cwpeaeppfqz.onion.

https://help.riseup.net/en/security/network-security/tor#riseups-tor-hidden-services

**Comment by sycamoreone** [comment]
This has already been fixed in c6635015bb411f8f72e1d849936b0a4220ed0511. You probably have to update (or reinstall):

    go get -u github.com/agl/xmpp-client
