### ISSUE TITLE
Online contacts list order

### ISSUE THREAD

**Issue by botherder** [agl/xmpp-client#80]
As I recently updated/reinstalled xmpp-client, my `roster --online` output stopped returning my contacts in alphabetic order but it appears they're ordered by date I added them as buddies. I looked at recent commit history and haven't found anything particular related to this.

Is this intentional or might it be unrelated to xmpp-client?

**Comment by agl** [comment]
I suspect that the server switched from returning a sorted list to returning it in some other order.

However, it's easy enough to have xmpp-client sort the entries when received. Done.
