### ISSUE TITLE
use godeps

### ISSUE THREAD

**Issue by david415** [agl/xmpp-client#85]
lock in the versions of the packages you depend on by using godep. https://github.com/tools/godep

Using godeps seems especially important in terms of being able to try historical versions of xmpp-client without the need to sift through various git commit logs to see compatible revisions of xmpp versus xmpp-client...

**Comment by agl** [comment]
I think moving xmpp into xmpp-client is a better answer and is overdue. Done in bd4c83f9b8259d357fb1613da5b93f50d8aa8576

**Comment by heavenlyhash** [comment]
Does that mean no more upstream updates to agl/xmpp?

...Ah, the repo is gone entirely.  Alright.  I'll be copy-forking your xmpp package into my gui project using it, then, I guess. :(

**Comment by agl** [comment]
> Alright. I'll be copy-forking your xmpp package into my gui project using it, then, I guess. :(

Yes please. I never planned on keeping API stability. It was just a useful, internal segmentation.
