### ISSUE TITLE
Failed to verify TLS certificate

### ISSUE THREAD

**Issue by samer** [agl/xmpp-client#88]
I'm using `go1.4.2 darwin/amd64`.
```
 * (10:49PM) Making TCP connection to jabberd.jabber.ccc.de.:5222
 * (10:49PM) Starting TLS handshake
 * (10:49PM) SSL/TLS version: TLS 1.2
 * (10:49PM) Cipher suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
 * (10:49PM) Failed to connect to XMPP server: xmpp: failed to verify TLS certificate: x509: certificate signed by unknown authority (possibly because of "x509: cannot verify signature: algorithm unimplemented" while trying to verify candidate authority certificate "CA Cert Signing Authority")
```
Ideas?

**Comment by rmoore** [comment]
Looks like you don't have the CAcert root certificate installed on your system (I don't believe it's included by default).  http://wiki.cacert.org/FAQ/ImportRootCert#Mac_OS_X

**Comment by samer** [comment]
Thanks Reese, that worked out. It's a new machine and I hadn't installed CAcert root cert yet. What's weird is that Adium connected just fine, even though "strict certificate checks" was on. Anyway, thanks again!

**Comment by superryanguo** [comment]
how to handle the same issue on Ubuntu?
$ uname -a
Linux ubuntu-16 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ ./xmpp-client 
Password for ppabb_189@0nl1ne.cc (will not be saved to disk): 
 * (4:54PM) Making TCP connection to 0nl1ne.cc.:5222
 * (4:54PM) Starting TLS handshake
 * (4:54PM)   SSL/TLS version: TLS 1.2
 * (4:54PM)   Cipher suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
 * (4:54PM) Failed to connect to XMPP server: xmpp: failed to verify TLS certificate: x509: certificate signed by unknown authority
