### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by pril** [agl/xmpp-client#89]
Hello,
I've tried the following steps accourting your installation 
1. sudo apt-get install git golang mercurial
2. export GOPATH=$HOME/go
3. go get github.com/agl/xmpp-client

I've expected that deh programm will be downloaded an executet at the 3rd Step. But I've got the following Message:
```bash
# github.com/agl/xmpp-client/xmpp
go/src/github.com/agl/xmpp-client/xmpp/xmpp.go:455: tlsState.Version undefined (type tls.ConnectionState has no field or method Version)
```
Maybe I've missed something, could you say what I'm doing wrong.

I'm using go in the version  go1.2.1 linux/386

**Comment by DrWhax** [comment]
You probably need go1.3.x in order to build xmpp-client.

**Comment by pril** [comment]
Thank you, DrWhax. xmpp-client runs with go version go1.4.2 linux/386
