### ISSUE TITLE
Xmpp-client not authenticating with Riseup 

### ISSUE THREAD

**Issue by tdruiva** [agl/xmpp-client#93]
Hi,

I think Riseup did some change in their server recently because xmpp-client stopped to work with it.
It's failing to authenticate.

Authentication log:
* (10:22AM) Making connection to 4cjw6cwpeaeppfqz.onion:5269 via proxy
 * (10:22AM) Starting TLS handshake
 * (10:22AM)   SSL/TLS version: TLS 1.2
 * (10:22AM)   Cipher suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
 * (10:22AM)   certificate 0: OU=Domain Control Validated/OU=PositiveSSL Wildcard/CN=*.riseup.net/
 * (10:22AM)   certificate 1: O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA/
 * (10:22AM)   certificate 2: O=COMODO CA Limited/CN=COMODO RSA Certification Authority/
 * (10:22AM) Authenticating as tdruiva
 * (10:22AM) Failed to connect to XMPP server: xmpp: PLAIN authentication is not an option

On `getFeatures`, this is the established stream:
xml.StartElement{Name:xml.Name{Space:"http://etherx.jabber.org/streams", Local:"stream"}, Attr:[]xml.Attr{xml.Attr{Name:xml.Name{Space:"xmlns", Local:"db"}, Value:"jabber:server:dialback"}, xml.Attr{Name:xml.Name{Space:"xmlns", Local:"stream"}, Value:"http://etherx.jabber.org/streams"}, xml.Attr{Name:xml.Name{Space:"", Local:"version"}, Value:"1.0"}, xml.Attr{Name:xml.Name{Space:"", Local:"from"}, Value:"riseup.net"}, xml.Attr{Name:xml.Name{Space:"", Local:"id"}, Value:"b674106a-4f5f-46e1-a276-d5eefdc8d5e1"}, xml.Attr{Name:xml.Name{Space:"", Local:"to"}, Value:""}, xml.Attr{Name:xml.Name{Space:"http://www.w3.org/XML/1998/namespace", Local:"lang"}, Value:"en"}, xml.Attr{Name:xml.Name{Space:"", Local:"xmlns"}, **Value:"jabber:server"**}}} 

And it's returning empty features.

I also use Gmail with xmpp-client (its working fine), looking their log the stream have a particular different `Value`. Their are returning `"jabber:client"` instead of `"jabber:server"` as Riseup did. 

I tried to force the authentication by plain skipping the `if !havePlain` but looks like their are not accepting it:
`Failed to connect to XMPP server: xmpp: authentication failure: invalid-mechanism`

**Comment by gusgr** [comment]
Hi, can you try to change the port to 5222?

xmpp.riseup.net:  4cjw6cwpeaeppfqz.onion (ports 5222, 5269)
https://help.riseup.net/en/tor

**Comment by micah** [comment]
5269 is for server to server connections, I dont think connecting a client to that port is going to work, try as @gusgr suggests

**Comment by tdruiva** [comment]
Through the port 5222 is not-authorized

 * (10:53AM) Making connection to 4cjw6cwpeaeppfqz.onion:5222 via proxy
 * (10:54AM) Starting TLS handshake
 * (10:54AM)   SSL/TLS version: TLS 1.2
 * (10:54AM)   Cipher suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
 * (10:54AM)   certificate 0: OU=Domain Control Validated/OU=PositiveSSL Wildcard/CN=*.riseup.net/
 * (10:54AM)   certificate 1: O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA/
 * (10:54AM)   certificate 2: O=COMODO CA Limited/CN=COMODO RSA Certification Authority/
 * (10:54AM) Authenticating as tdruiva
 * (10:54AM) Failed to connect to XMPP server: xmpp: authentication failure: not-authorized

**Comment by gusgr** [comment]
@tdruiva, it's working for me. maybe wrong password?

**Comment by tdruiva** [comment]
You're right.
Dammit copy+paste from pass manager 
![facepalm](http://i.giphy.com/OdPPP31Z5zBNS.gif)

Tks!
